#tenta exceutar o que est√° dentro do try, se der erro, aprensenta o except

try:
    arquivo = open('arquivo2')
except:
    print('Desculpe, algo deu errado')
